### ISSUE TITLE
Add option to edit todo item

### ISSUE THREAD

**Issue by annabjurback** [annabjurback/todo_w_xunit_tests#16]
Add edit button, when clicked open up an input form and a save button.
- [x] create edit method
- [x] create red test edit method
- [x] retest and refactor edit method
- [x] handle request if null
- [x] red test handle request if null
- [x] retest and refactor handle request if null
- [x] implement functionality on page
