### ISSUE TITLE
Create Todo

### ISSUE THREAD

**Issue by annabjurback** [annabjurback/todo_w_xunit_tests#3]
- [x] Return todo result with same value as request
- [x] create red test Return todo result with same value as request
- [x] retest and refactor Return todo result with same value as request
- [x] Handle request if null
- [x] create red test Handle request if null
- [x] retest and refactor Handle request if null
- [x] test that autoincrement of ID works properly
- [x] return success flag on result
- [x] Fix CI Pipeline before merging to main
