### ISSUE TITLE
Delete Todo

### ISSUE THREAD

**Issue by annabjurback** [annabjurback/todo_w_xunit_tests#4]
- [x] create button for deleting todo
- [x] return Status code on delete
- [x] create red test return Status code on delete
- [x] retest and refactor return Status code on delete
- [x] Handle request if null
- [x] create red test Handle request if null
- [x] retest and refactor Handle request if null
- [x] Handle request if !int
- [x] create red test Handle request  if !int
- [x] retest and refactor Handle request if !int
- [x] return success flag on result

- [x] handle the case when an id is sent that does not exist in the list
  - [x] red test
  - [x] refactor and retest
